import httpx
import asyncio
import logging
import os
import re
from typing import List

logger = logging.getLogger(__name__)


class GitHubService:
    def __init__(self, token: str):
        self.token = token
        self.headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
        }
        self.api_url = "https://api.github.com"

    def _parse_repo(self, repo_url: str):
        """Extract owner/repo from GitHub URL"""
        match = re.search(r"github\.com[/:]([^/]+)/([^/\\.]+)", repo_url)
        if not match:
            raise ValueError(f"Cannot parse GitHub URL: {repo_url}")
        return match.group(1), match.group(2).replace(".git", "")

    async def get_default_branch(self, owner: str, repo: str) -> str:
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.get(f"{self.api_url}/repos/{owner}/{repo}", headers=self.headers)
            data = resp.json()
            return data.get("default_branch", "main")

    async def create_pr(self, repo_url: str, repo_dir: str, analysis_id: str, fixes: list) -> str:
        owner, repo = self._parse_repo(repo_url)
        branch_name = f"repodoctor/fix-{analysis_id[:8]}"

        # Configure git in repo dir
        async def run_git(*args):
            proc = await asyncio.create_subprocess_exec(
                "git", *args,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=repo_dir
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=30)
            return proc.returncode, stdout.decode(), stderr.decode()

        # Set up git identity
        await run_git("config", "user.email", "repodoctor@bot.ai")
        await run_git("config", "user.name", "RepoDoctor")

        # Create and checkout new branch
        code, out, err = await run_git("checkout", "-b", branch_name)
        if code != 0:
            raise Exception(f"Failed to create branch: {err}")

        # Add all changes
        await run_git("add", "-A")
        
        # Build commit message
        fixed_files = list(set(f.get("file", "") for f in fixes if f.get("verified")))
        commit_msg = f"fix: resolve {len([f for f in fixes if f.get('verified')])} bug(s) found by RepoDoctor\n\nFixed files: {', '.join(fixed_files[:5])}"
        
        code, out, err = await run_git("commit", "-m", commit_msg)
        if code != 0:
            raise Exception(f"Failed to commit: {err}")

        # Push with token auth
        auth_url = repo_url.replace("https://", f"https://{self.token}@").replace("http://", f"http://{self.token}@")
        if not auth_url.endswith(".git"):
            auth_url += ".git"
        
        code, out, err = await run_git("push", auth_url, branch_name)
        if code != 0:
            raise Exception(f"Failed to push: {err}")

        # Create PR via GitHub API
        default_branch = await self.get_default_branch(owner, repo)
        bug_summary = "\n".join([f"- {f.get('explanation', 'Bug fixed')}" for f in fixes[:5] if f.get("verified")])
        
        pr_body = f"""## RepoDoctor Autonomous Fix

This PR was automatically generated by **RepoDoctor** - an autonomous bug fixing agent.

### Bugs Fixed
{bug_summary}

### How it works
1. Cloned repository and mapped file structure
2. Ran tests and lint checks to identify failures  
3. Used AI to generate minimal fixes
4. Verified each fix by re-running the tests
5. Created this PR automatically

---
*Generated by RepoDoctor | Analysis ID: `{analysis_id[:8]}`*
"""
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.post(
                f"{self.api_url}/repos/{owner}/{repo}/pulls",
                headers=self.headers,
                json={
                    "title": f"fix: {len([f for f in fixes if f.get('verified')])} bug(s) fixed by RepoDoctor",
                    "body": pr_body,
                    "head": branch_name,
                    "base": default_branch,
                },
            )
            data = resp.json()
            if "html_url" not in data:
                raise Exception(f"PR creation failed: {data.get('message', 'Unknown error')}")
            return data["html_url"]
